### ISSUE TITLE
Указание загрузчика | автоматическое определение

### ISSUE THREAD

**Issue by ArviZ** [Davert94/install-hook#4]
реквестирую выпил вгета как постоянного загрузчика и возможность задать оного через переменную окружения заменил в вызове установщика на курл, внутри жестко указан wget)
в системе нет wget
можно сделать параметром для установщика: (wget|curl|auto)

**Comment by DavertTanz** [comment]
@ArviZ, сделал примитивно на текущий момент. Если wget нет, то используем curl. Обновил также README.md - проверяй

**Comment by ArviZ** [comment]
👍
